### PR TITLE
ADR-0004 - Error Codes for Handled Exceptions

### PR DESCRIPTION
**Pull request by RossMurr4y**
This ADR proposes that Error Codes be implemented across Hamlet Deploy to enable greater support, troubleshooting and documentation for handled exceptions.

### CODE REVIEW

**Comment by roleyfoley** [comment]
@RossMurr4y To progress this please arrange a discussion to go through fleshing this out

**Comment by RossMurr4y** [comment]
I believe @ml019 has made some progress towards this one as it has come up during the last few stand-ups.

I will organise a discussion for this week.

**Comment by ken9ross** [comment]
I'd suggest the enumeration of the error codes should be something that can be used to report the details from the failure, so that the "manually-maintained library of error codes" becomes a "utility that reports information on the error" (techs are more likely to maintain a utility than documentation)

**Comment by RossMurr4y** [comment]
Meeting with @hamlet-io/engine-maintainers held on 2.3.21

**Questions raised**
Q: should we be writing "trace" information out to file as we pass through the engine, to capture the engine output and clean up the outputs a bit?

A: deemed to be unrelated at this time to this ADR.

**Suggestions**
- introduce classes of errors to handle the types of errors that we are already seeing
  - we at a later time might re-evaluate this and extend this to providing exception codes
  - include a source-prefix for the origin of the error i.e "e" for "engine", "t" for "task runner" etc.

**Decision**
- Introduce logging classes (not purely for exceptions/errors).
- All log messages must be associated with one of a list of given classes
- The classes will have a prefix for each of the possible logging sources (i.e "e" = "engine", "t" = "task" etc)
- At a later stage we will evaluate if it is necessary / still useful to implement specific error codes and we will be able to build upon this framework

**Review by roleyfoley — APPROVED** [review]

**Pull request merged**
